import axios from 'axios';
import db from './db.js';

export async function generateAIAnalysis(documentData) {
  try {
    // Get OpenRouter API key from settings
    const settings = await db.getSetting('openrouter_api_key');

    if (!settings || !settings.value || settings.value === '""') {
      console.log('OpenRouter API key not configured, skipping AI analysis');
      return null;
    }

    const apiKey = settings.value.replace(/"/g, '');

    const response = await axios.post(
      'https://openrouter.ai/api/v1/chat/completions',
      {
        model: 'openai/gpt-3.5-turbo',
        messages: [
          {
            role: 'system',
            content: 'You are a tax and salary analysis expert. Analyze Form-16 data and provide insights in JSON format.',
          },
          {
            role: 'user',
            content: `Analyze this Form-16 data and provide:
1. Salary summary (gross, net, deductions, take_home)
2. Tax summary (total_tax, tds, tax_paid, refund_or_payable)
3. Investment summary (total_investments, section_80c, other_deductions)
4. Key observations (array of strings)
5. Employee-friendly explanation (simple text)

Data: ${JSON.stringify(documentData)}

Respond in JSON format only.`,
          },
        ],
      },
      {
        headers: {
          'Authorization': `Bearer ${apiKey}`,
          'Content-Type': 'application/json',
        },
      }
    );

    const analysisText = response.data.choices[0].message.content;
    
    // Try to parse JSON response
    try {
      return JSON.parse(analysisText);
    } catch {
      // If not JSON, create structured response
      return {
        salary_summary: {
          gross_salary: documentData.gross_salary || 0,
          net_salary: documentData.net_salary || 0,
          deductions: 0,
          take_home: documentData.net_salary || 0,
        },
        tax_summary: {
          total_tax: documentData.tax_paid || 0,
          tds: documentData.tds || 0,
          tax_paid: documentData.tax_paid || 0,
          refund_or_payable: 0,
        },
        investment_summary: {
          total_investments: 0,
          section_80c: documentData.deductions?.['80C'] || 0,
          other_deductions: 0,
        },
        observations: ['Analysis generated by AI'],
        employee_explanation: analysisText,
      };
    }
  } catch (error) {
    console.error('AI analysis error:', error.message);
    return null;
  }
}

export async function chatWithDocument(documentId, question) {
  try {
    // Get document metadata
    const metadata = await db.getDocumentMetadata(documentId);

    if (!metadata) {
      return 'Document data not found.';
    }

    const documentData = metadata.parsed_json;

    // Get OpenRouter API key
    const settings = await db.getSetting('openrouter_api_key');

    if (!settings || !settings.value || settings.value === '""') {
      // Fallback to keyword matching
      return keywordBasedAnswer(documentData, question);
    }

    const apiKey = settings.value.replace(/"/g, '');

    const response = await axios.post(
      'https://openrouter.ai/api/v1/chat/completions',
      {
        model: 'openai/gpt-3.5-turbo',
        messages: [
          {
            role: 'system',
            content: `You are a helpful assistant that answers questions about Form-16 documents. 
                     Only answer based on the provided document data. 
                     If the information is not in the document, say "Not available in your Form-16."
                     Do not make up or hallucinate information.`,
          },
          {
            role: 'user',
            content: `Document data: ${JSON.stringify(documentData)}
                     
                     Question: ${question}`,
          },
        ],
      },
      {
        headers: {
          'Authorization': `Bearer ${apiKey}`,
          'Content-Type': 'application/json',
        },
      }
    );

    return response.data.choices[0].message.content;
  } catch (error) {
    console.error('Chat error:', error.message);
    return 'Unable to process your question at this time.';
  }
}

function keywordBasedAnswer(data, question) {
  const questionLower = question.toLowerCase();

  // Gross Salary
  if (questionLower.includes('gross salary') || questionLower.includes('कुल वेतन')) {
    return data.gross_salary
      ? `Your gross salary is ₹${data.gross_salary.toLocaleString()}`
      : 'Not available in your Form-16.';
  }

  // Net Salary
  if (questionLower.includes('net salary') || questionLower.includes('नेट वेतन')) {
    return data.net_salary
      ? `Your net salary is ₹${data.net_salary.toLocaleString()}`
      : 'Not available in your Form-16.';
  }

  // Tax/TDS
  if (questionLower.includes('tax') || questionLower.includes('tds') || questionLower.includes('कर')) {
    if (data.tds) {
      return `Your TDS (Tax Deducted at Source) is ₹${data.tds.toLocaleString()}`;
    }
    return 'Not available in your Form-16.';
  }

  // PAN
  if (questionLower.includes('pan')) {
    return data.pan ? `Your PAN is ${data.pan}` : 'Not available in your Form-16.';
  }

  // Employer
  if (questionLower.includes('employer') || questionLower.includes('नियोक्ता')) {
    return data.employer_name
      ? `Your employer is ${data.employer_name}`
      : 'Not available in your Form-16.';
  }

  // Financial Year / Year
  if (questionLower.includes('financial year') || questionLower.includes('year') || questionLower.includes('साल')) {
    return data.financial_year || data.assessment_year
      ? `The financial year is ${data.financial_year || data.assessment_year}`
      : 'Not available in your Form-16.';
  }

  // Deductions
  if (questionLower.includes('deduction') || questionLower.includes('कटौती')) {
    if (data.deductions && Object.keys(data.deductions).length > 0) {
      const deductionText = Object.entries(data.deductions)
        .map(([key, value]) => `${key}: ₹${value.toLocaleString()}`)
        .join(', ');
      return `Your deductions are: ${deductionText}`;
    }
    return 'Not available in your Form-16.';
  }

  // Investments / 80C
  if (questionLower.includes('investment') || questionLower.includes('80c') || questionLower.includes('निवेश')) {
    if (data.investments && Object.keys(data.investments).length > 0) {
      const investmentText = Object.entries(data.investments)
        .map(([key, value]) => `${key}: ₹${value.toLocaleString()}`)
        .join(', ');
      return `Your investments are: ${investmentText}`;
    }
    return 'Not available in your Form-16.';
  }

  // Employee Name
  if (questionLower.includes('name') || questionLower.includes('नाम')) {
    return data.employee_name
      ? `Your name as per Form-16 is ${data.employee_name}`
      : 'Not available in your Form-16.';
  }

  return `I can help you with information about: Gross Salary, Net Salary, Tax/TDS, PAN, Employer, Financial Year, Deductions, Investments, and Employee Name. What would you like to know?`;
}
